# Even though we run everything inside docker Travis require
# us to pick a language else it will pick Ruby by default
language: generic

# Omit running tests on temporal branches
branches:
  except:
    - /^tmp/

env:
  global:
    - TEST_SLEEPS="0.7"

matrix:
  include:
    # Linux with docker:stable compose:stable
    - os: linux
      sudo: required
      services:
        - docker
      env:
        - DOCKER_VERSION="stable"
          DOCKER_COMPOSE_VERSION="1.7.1"
          DOCKER_PUSH=true
    # Linux with docker:beta compose:stable
    - os: linux
      sudo: required
      services:
        - docker
      env:
        - DOCKER_VERSION="1.12.0-rc3"
          DOCKER_COMPOSE_VERSION="1.7.1"
    # Linux with docker:stable compose:beta
    - os: linux
      sudo: required
      services:
        - docker
      env:
        - DOCKER_VERSION="stable"
          DOCKER_COMPOSE_VERSION="1.8.0-rc1"
    # Linux with docker:beta compose:beta
    - os: linux
      sudo: required
      services:
        - docker
      env:
        - DOCKER_VERSION="1.12.0-rc3"
          DOCKER_COMPOSE_VERSION="1.8.0-rc1"
    - os: osx
      osx_image: xcode8
      env:
        - DOCKER_VERSION="1.12.0-rc3"
          DOCKER_COMPOSE_VERSION="1.8.0-rc1"

before_install:
  - travis_retry ./test/before_install_setup
  - travis_retry ./test/before_install_build

install:
  - ./test/install

script:
  - ./test/script

# cleanup though doesn't seem to be necessary in Travis infra
after_script:
  - ./test/after_script
